# Generated by Django 4.0.6 on 2022-09-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('number_of_slots', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChargingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('charge_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('otp', models.IntegerField()),
                ('battery_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.battery')),
                ('charging_station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='charging_stations.chargingstation')),
                ('vehicle_alloted', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.vehicle')),
            ],
        ),
    ]
