# Generated by Django 4.0.6 on 2022-09-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
