# Generated by Django 4.0.6 on 2022-09-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battery',
            old_name='batter_name',
            new_name='battery_name',
        ),
    ]
